services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/view/node_module
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.django.local
      - DJANGO_DEBUG=True
      - PYTHONUNBUFFERED=1
    env_file:
      - .env

  frontend:
    build:
      context: ./view
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./view:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000/api